### ISSUE TITLE
sorry, It seem that some of the links are invaild, could you please update them?

### ISSUE THREAD

**Issue by 18924262526** [yunzhusong/ECCV2020_CPCSV#24]
When I try to download the dataset, it failed. It seem that some of the links are invaild, could you please update them?

**Comment by yunzhusong** [comment]
Hi, thanks for the reminder! We have updated the links.

**Comment by 18924262526** [comment]
谢谢啦。

**Comment by yunzhusong** [comment]
Thank you.
